---
abstract: 'Simple backend-independent plotting for PDL'
author:
  - 'Craig DeForest <craig@deforest.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PDL-Graphics-Simple
no_index:
  directory:
    - t
    - inc
requires:
  File::Temp: 0
  PDL: 0
  Test::More: 0
  Time::HiRes: 0
resources:
  homepage: http://github.com/drzowie/PDL-Graphics-Simple
  repository: git://github.com/drzowie/PDL-Graphics-Simple.git
version: 1.004
